services:
  backend:
    build:
      context: ./backend
    container_name: budget-app-backend
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - llm_microservice
    volumes:
      - ./backend/app/llm_microservice/.env:/app/llm_microservice/.env
  
  frontend:
    build:
      context: ./frontend
    container_name: budget-app-frontend
    expose:
      - "3000"
    depends_on:
      - backend
  
  llm_microservice:
    build:
      context: ./backend/app/llm_microservice
    container_name: llm-microservice
    expose:
      - "8001"
    volumes:
      - ./backend/app/llm_microservice/.env:/app/.env
  
  graph_microservice:
    build:
      context: ./backend/app/graph_microservice
    container_name: graph-microservice
    expose:
      - "8002"
    depends_on:
      - backend
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: budget-app-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - llm_microservice
      - graph_microservice