version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: budget-app-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: budget-app-frontend
    ports:
      - "3000:80" # Map port 3000 on the host to port 80 in the container
    depends_on:
      - backend # Ensure the backend service is started before the frontend
